# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
PATH="$HOME/gcc/:$PATH"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# History for multiple terminals
export PROMPT_COMMAND="history -a"

# MATLAB env variables
export GTK_PATH=/usr/lib64/gtk-2.0
export LIBOVERLAY_SCROLLBAR=0
export GIO_EXTRA_MODULES=/usr/lib64/gio/modules

# User specific aliases and functions
alias sudo="sudo "
alias clean="clean.sh"
alias setup_gcc="setup_gcc.sh"
alias mymake="CC=gcc4 CXX=g++4 cmake . -DCMAKE_BUILD_TYPE=Release && make -j"
alias mymakedebug="CC=gcc4 CXX=g++4 cmake . -DCMAKE_BUILD_TYPE=Debug && make -j"
alias makev="make_verb.sh"
alias test="ctest --output-on-failure"
alias test_v="ctest --output-on-failure -V"
alias test_vv="ctest --output-on-failure -VV"
