# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
PATH="$HOME/gcc/:$PATH"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias sudo="sudo "
alias clean="clean.sh"
alias setup_gcc="setup_gcc.sh"
alias mymake="CC=gcc4 CXX=g++4 cmake . && make -j"
alias makev="make_verb.sh"
alias test="ctest --output-on-failure"
alias test_v="ctest --output-on-failure -V"
alias test_vv="ctest --output-on-failure -VV"
